export const Sport = [
  {
    img: "/assets/briskw.jpg",
    name: "brisk walking",
    duration: "10 - 15 min",
    description: [
      "Physical activity doesn't need to be complicated. Something as simple as a daily brisk walk can help you live a healthier life.",
      " For example, regular brisk walking can help you:",
      "- Maintain a healthy weight",
      "- Prevent or manage various conditions, including heart disease, high blood pressure and type 2 diabetes",
      "- Strengthen your bones and muscles",
      "- Improve your mood",
      "- Improve your balance and coordination",
      "- The faster, farther and more frequently you walk, the greater the benefits",
      "- You do not have to walk for hours. A brisk 10-minute daily walk has lots of health benefits and counts towards your recommended 150 minutes of weekly exercise.",
    ],
  },
  {
    img: "/assets/swim.jpg",
    name: "swimming",
    duration: 0,
    description: [
      "Swimming is a great physical activity for people with diabetes and hypertension. Not only is it fun, it has several benefits .",
      "- Swimming improves cardiovascular fitness.",
      "- Swimming also burns calories and can help control weight, which is also important for diabetics.",
      "- Swimming strengthens all the major muscles in the body, which is valuable in controlling diabetes.",
      "- When exercising, muscle cells more efficiently absorb blood sugar. This is how exercising lowers blood sugar levels.",
      "- The glucose control benefits from exercise can last for hours -- or sometimes days - but they are not permanent. This is why getting exercise regularly is more important for people with diabetes than is working out more intensely, but less frequently.",
    ],
  },
  {
    img: "/assets/cycl.jpg",
    name: "cycling",
    duration: 0,
    description: [
      "Cycling is a healthy, low-impact exercise that can be enjoyed by people of all ages, from young children to older adults.",
      "- It only takes two to four hours a week to achieve a general improvement to your health.",
      "Cycling is: ",
      "- Low impact .",
      "- it causes less strain and injuries than most other forms of exercise.",
      "- A good muscle workout .",
      "- cycling uses all of the major muscle groups as you pedal.",
      "-  Easy unlike some other sports.",
      "- cycling increases stamina, strength and aerobic fitness. ",
      "- cycling can be done at very low intensity to begin with.",
      "- Time-efficient .",
      "- As a mode of transport, cycling replaces sedentary (sitting) time spent driving motor vehicles or using trams, trains....",
    ],
  },
];
